# Generated by Django 4.2.4 on 2025-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('dietitian', 'Dietitian'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
