# Generated by Django 5.2.4 on 2025-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_cities_options_alter_professions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dietician_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
