# Generated by Django 5.2.4 on 2025-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_dob_account_gender_account_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
